apiVersion: apps/v1
kind: Deployment
metadata:
  name: emt-app
  namespace: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emt-app
  template:
    metadata:
      labels:
        app: emt-app
    spec:
      containers:
        - name: app
          image: alekso93/kiiapp:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: db-secret
