apiVersion: v1
kind: Service
metadata:
  name: emt-app-service
  namespace: bookstore
spec:
  selector:
    app: emt-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
