services:
  db:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: emt
      POSTGRES_PASSWORD: emt
      POSTGRES_DB: emt_shop
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./views.sql:/docker-entrypoint-initdb.d/views.sql
    ports:
      - "2345:5432"
  app:
    build: .
    container_name: kiiapp
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/emt-shop
      SPRING_DATASOURCE_USERNAME: emt
      SPRING_DATASOURCE_PASSWORD: emt
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
volumes:
  pgdata:
