name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  maven-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build app with Maven
        run: mvn clean install -DskipTests -B
        working-directory: ./e-shop-backend-main

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-artifact
          path: e-shop-backend-main/target/*.jar

  build-push-docker:
    needs: maven-build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: app-artifact
          path: e-shop-backend-main/target/

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check DOCKER_USERNAME presence
        run: |
          if [ -z "${DOCKER_USERNAME}" ]; then
            echo "DOCKER_USERNAME NOT SET"
            exit 1
          else
            echo "DOCKER_USERNAME is set"
          fi
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Build and push container image to DockerHub
        uses: docker/build-push-action@v3
        with:
          context: ./e-shop-backend-main
          push: true
          file: ./e-shop-backend-main/Dockerfile
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/kiiapp:latest

